---
- name: Capture git event
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.dashes_to_underscores:

  rules:
    - name: check for payload
      condition: event.payload is defined 
      action:
        debug: 

    - name: check for ref_type
      condition: event.payload[0].ref_type is defined
      action: 
        debug: "{{ event.payload[0].ref_type}}"