---
- name: Capture git event
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.dashes_to_underscores:

  rules:
    - name: check for payload
      condition: event.payload is defined 
      action:
        debug: 

    - name: check for ref_type
      condition: event.meta.headers.X_GitHub_Event == "create"
      action: 
        debug: 
    
    - name: check for forking
      condition: event.meta.headers.X_GitHub_Event == "fork"
      action:
        debug: 